### ISSUE TITLE
Setting up intagration ends in error

### ISSUE THREAD

**Issue by prchal** [ekutner/home-connect-hass#109]
Hi,
for a while I'm not able to set up this integration.
I start the process, then I need to fix the redirect request to https://myaddr.tld:8123/auth/external/callback, then I log in to home connect, grant access but return back to HA ends in "error".
Here is my log:
`2022-09-08 11:24:18.343 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/home/homeassistant/venv_3.9.7/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/home/homeassistant/venv_3.9.7/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/home/homeassistant/venv_3.9.7/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/home/homeassistant/venv_3.9.7/lib/python3.9/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/home/homeassistant/venv_3.9.7/lib/python3.9/site-packages/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/home/homeassistant/venv_3.9.7/lib/python3.9/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/home/homeassistant/venv_3.9.7/lib/python3.9/site-packages/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/home/homeassistant/venv_3.9.7/lib/python3.9/site-packages/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/home/homeassistant/venv_3.9.7/lib/python3.9/site-packages/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/home/homeassistant/venv_3.9.7/lib/python3.9/site-packages/homeassistant/components/config/config_entries.py", line 169, in get
    return await super().get(request, flow_id)
  File "/home/homeassistant/venv_3.9.7/lib/python3.9/site-packages/homeassistant/helpers/data_entry_flow.py", line 96, in get
    result = await self._flow_mgr.async_configure(flow_id)
  File "/home/homeassistant/venv_3.9.7/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 280, in async_configure
    result = await self._async_handle_step(
  File "/home/homeassistant/venv_3.9.7/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/home/homeassistant/venv_3.9.7/lib/python3.9/site-packages/homeassistant/helpers/config_entry_oauth2_flow.py", line 303, in async_step_creation
    token = await self.flow_impl.async_resolve_external_data(self.external_data)
  File "/home/homeassistant/venv_3.9.7/lib/python3.9/site-packages/homeassistant/helpers/config_entry_oauth2_flow.py", line 169, in async_resolve_external_data
    return await self._token_request(
  File "/home/homeassistant/venv_3.9.7/lib/python3.9/site-packages/homeassistant/helpers/config_entry_oauth2_flow.py", line 205, in _token_request
    resp.raise_for_status()
  File "/home/homeassistant/venv_3.9.7/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.home-connect.com/security/oauth/token')
`
Could someone help me, please?

**Comment by ekutner** [comment]
Follow the setup instructions. You shouldn't have to change the URL.

**Comment by stepscout** [comment]
Using the documented URL `https://my.home-assistant.io/redirect/oauth` works for me even-though I do not use the Home Assistant Cloud. During configuration of the integration it opens a browser window for the authorization of the API integration by Home Connect developer portal. This cause an error when the redirect URL is wrongly configured in the Home Connect Application on the portal (editing the URL in the browser bar is not a workaround). Make sure to set the URL according documentation. Be aware that the error can persist for a while after correcting the URL. Give it 30 minutes if needed.

**Comment by nordicgit70** [comment]
Using the documented URL https://my.home-assistant.io/redirect/oauth works for me even-though I do not use the Home Assistant Cloud. During configuration of the integration it opens a browser window for the authorization of the API integration by Home Connect developer portal. This cause an error when the redirect URL is wrongly configured in the Home Connect Application on the portal (editing the URL in the browser bar is not a workaround). Make sure to set the URL according documentation. Be aware that the error can persist for a while after correcting the URL. Give it 30 minutes if needed.

**Comment by prchal** [comment]
Surely I followed the setup instructions. But I changed the url to my addr in mind that I don't have cloud so this must be my addr.
So it works now.
Thanks a lot.

**Comment by hqxdxy233** [comment]
I found that the URL cannot use the HTTPS protocol. How can I solve this problem?

**Comment by prchal** [comment]
My is ok with it.

**Comment by hqxdxy233** [comment]
> 

T_T  Thank you. I'll try again.
