### ISSUE TITLE
Setup Issue - Error handling request

### ISSUE THREAD

**Issue by danbayliss** [ekutner/home-connect-hass#24]
I can't seem to get this custom integration to see any of my devices. I've had the inbuilt Home Connect integration working fine for some time now but when I try and set this up it just creates the 3 built in entities (Debug, Refresh & Status). When setting up it takes me to the Home Connect portal and when I click approve it takes me back to my HA instance but the page is completely blank. If I refresh the bank page it gives me a "500 Internal Server Error"

My logs show the following errors
```
22-05-29 14:06:48 INFO (MainThread) [custom_components.home_connect_alt.config_flow] Successfully authenticated
2022-05-29 14:06:48 DEBUG (MainThread) [home_connect_async.api] HTTP get /api/homeappliances (code=200  count=1)
2022-05-29 14:06:48 DEBUG (MainThread) [home_connect_async.homeconnect] Connecting to SSE stream
2022-05-29 14:06:52 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 409, in get
    await hass.config_entries.flow.async_configure(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 246, in async_configure
    raise UnknownFlow
homeassistant.data_entry_flow.UnknownFlow
```

When I press the debug button I get
```
2022-05-29 14:06:59 ERROR (MainThread) [custom_components.home_connect_alt.button] {
  "appliances": {}
}
```

I've tried waiting 24 hours in case the issue was with rate limiting but i'm still seeing the same. Any ideas?

**Comment by ekutner** [comment]
I'm not sure exactly what's going on but it seems the integration is getting an empty response from the Home Connect API and is also unable to connect to the SSE endpoint in order to receive event notifications. Thus us most likely caused by something wrong in the app setup on Home Connect. Make sure it is configured correctly them remove the Home Connect Alt integration from HA and add it back again, see if that fixes it.
By the way, the empty page when finishing the login flow through HC is expected, that's fine.

**Comment by danbayliss** [comment]
As I was previously using the built in integration I only renamed the line in configuration.yaml to add '_alt' at the end so would assume the app is setup correctly. As a test I setup a new app on Home Connect and updated configuration.yaml but the same issue was happening so I removed this custom integration and was able to add the built in integration and my 3 devices were immediately available.

I wonder if running NGINX proxy is causing this issue? It's so I can use HTTP internally and HTTPS externally. The app is setup to use the external address so I make sure when adding the integration i'm accessing HA using the external address
![hwyAvYJ](https://user-images.githubusercontent.com/54558493/170891873-9d3397b5-d930-48ab-9910-3e1426f470f4.png)
![2YboPMM](https://user-images.githubusercontent.com/54558493/170891894-bbf4c76b-4bdf-4af0-af01-ddba9a8063b4.png)

**Comment by ekutner** [comment]
I'm not sure if it's related or not. Try clicking the Home Connect Refresh button and upload the complete log.

**Comment by canedje** [comment]
did you also install the new home connect alt integration at the integration page?
(I forgot to do that myself)

**Comment by danbayliss** [comment]
I removed the official integration, added '_alt' in configuration.yaml, installed this custom integration and restarted. I then added this integration in the HA devices page, logged into Home Connect, pressed approve and received the blank page.

The good news is one of my devices is now available, two are not but i'm assuming this could be due to the rate limit so I will leave it 24 hours to see what happens

**Comment by ekutner** [comment]
Good news indeed, it means you have successfully connected. It is unlikely that the missing appliances are because of rate limits. Make sure they are powered on and connected to the internet (you can check on the home connect mobile app but make sure you are NOT connected to your home WiFi when you check). If these appliances are active in the app then please upload a debug log.

**Comment by danbayliss** [comment]
The devices appeared in Home Connect but turning off my WiFi the two missing devices then showed as disconnected. I've set them both up again and they now appear in this custom integration so issue now resolved. I've got some missing translations but I will submit them as a pull request shortly

**Comment by labaland** [comment]
Is it no possible to use "https://my.home-assistant.io/redirect/oauth" as url ?
