### ISSUE TITLE
Cooker Hood - Program Select

### ISSUE THREAD

**Issue by danbayliss** [ekutner/home-connect-hass#30]
When I try and select the program for my cooker hood I get an error message. In additional when the hood is running the program select is greyed out so I can't switch to delayed shut down (which is possible with the official integration)

## Dashboard
![2xuSO2g](https://user-images.githubusercontent.com/54558493/171261929-9f8a2ddc-a36d-4ae0-b6c3-cdc39817ac0a.png)

## Log

```

2022-05-31 19:44:01 DEBUG (MainThread) [home_connect_async.homeconnect] Received event from SSE stream: MessageEvent(type='KEEP-ALIVE', message='KEEP-ALIVE', data='', origin='https://api.home-connect.com', last_event_id='BOSCH-DWK98PR60B-XXXXX')
2022-05-31 19:44:34 DEBUG (MainThread) [home_connect_async.appliance] Calling /api/homeappliances/BOSCH-DWK98PR60B-XXXXX/programs/selected with:
{
  "data": {
    "key": "Cooking.Common.Program.Hood.Venting",
    "options": []
  }
}
2022-05-31 19:44:34 DEBUG (MainThread) [home_connect_async.api] HTTP put /api/homeappliances/BOSCH-DWK98PR60B-XXXXX/programs/selected (code=409  count=339)
2022-05-31 19:44:34 DEBUG (MainThread) [home_connect_async.api] API call failed with code=409 error=SDK.Error.ProgramNotWritable
2022-05-31 19:44:34 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140603455320992] Failed to set the selected program: Program can currently not be written (409 - None=Cooking.Common.Program.Hood.Venting)
Traceback (most recent call last):
  File "/config/custom_components/home_connect_alt/select.py", line 102, in async_select_option
    await self._appliance.async_select_program(key=option)
  File "/usr/local/lib/python3.9/site-packages/home_connect_async/appliance.py", line 219, in async_select_program
    res = await self._async_set_program(key, options, 'selected')
  File "/usr/local/lib/python3.9/site-packages/home_connect_async/appliance.py", line 368, in _async_set_program
    raise HomeConnectError(response.error_description, response=response)
home_connect_async.common.HomeConnectError: ('Program can currently not be written', None, 'SDK.Error.ProgramNotWritable', 'Program can currently not be written', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 189, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1627, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1664, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 54, in async_select_option
    await entity.async_select_option(option)
  File "/config/custom_components/home_connect_alt/select.py", line 105, in async_select_option
    raise HomeAssistantError(f"Failed to set the selected program: {ex.error_description} ({ex.code} - {self._key}={option})")
homeassistant.exceptions.HomeAssistantError: Failed to set the selected program: Program can currently not be written (409 - None=Cooking.Common.Program.Hood.Venting)



```

**Comment by crhammock** [comment]
Just want to say I am very excited about this integration.  I have been trying to automate my oven for over 12 months and have a pretty good handle on the API using things like postman and curl but can't get the built integration to do what I want.

If you want to change the behaviour of the active program you need to use https://api.home-connect.com/api/homeappliances/{MYHAID}/programs/active/options/ I would suggest this needs to be exposed as a service and if possible the dashboard switches and settings should check first if an active program is running and if it is call this service.

**Comment by danbayliss** [comment]
I've checked the Home Connect app and the official Home Connect integration and can confirm they can change the program whilst the hood is on. I mainly use this when the hood is on and I want to turn on delayed shut down so my cooker hood turns off after 10 minutes
![y3OvQ7p](https://user-images.githubusercontent.com/54558493/171735216-af24e290-270c-4819-9db0-649a9d5683fd.png)

I'm going to open a seperate issue with the error message so we can use this issue to track the ability to select a program whilst the hood is on

**Comment by ekutner** [comment]
This is the same problem as #34 so I'm going to close this one and track the resolution on the other issue
