### ISSUE TITLE
Missing module home_connect_async after update Core to 2024.12

### ISSUE THREAD

**Issue by mkshb** [ekutner/home-connect-hass#454]
## Describe the bug
After upgrading HA to 2024.12 module home_connect_async is missing. I can download it with pip and it is there when I reload. If I restart my container, the module is gone again.

## Version of the custom_component
2024.12.2, last working version 2024.11

## Debug log
```
Logger: homeassistant.setup
Quelle: setup.py:334
Erstmals aufgetreten: 09:23:38 (1 Vorkommnisse)
Zuletzt protokolliert: 09:23:38

Setup failed for custom integration 'home_connect_alt': Unable to import component: No module named 'home_connect_async'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/home_connect_alt/__init__.py", line 11, in <module>
    from home_connect_async import Appliance, HomeConnect, Events, ConditionalLogger
ModuleNotFoundError: No module named 'home_connect_async'
```

**Comment by ekutner** [comment]
This is not related to the integration. HA is handling the download of dependencies. I assume your log should also have some HA error that would explain why it failed to download it.

**Comment by Ra72xx** [comment]
I have the same problem. I have quite a few custom integrations, and this is the only one with this error, I see no other error in the HA logs.

**Comment by mkshb** [comment]
Here are also no other errors in the log that would indicate a problem with HA. However, I have this with two other integrations, so it could already be a structural problem.

**Comment by mkshb** [comment]
You are right. It is a Home Assistant core problem after all. 

It is related to the 2024.12 update, more precisely to Python 3.13 and the switch from pip to uv. And this is in interaction with Docker or containers in general.

It is described in more detail in this thread: https://community.home-assistant.io/t/wth-is-going-on-with-docker-container-installs-and-third-party-integrations-that-need-python-modules/806430
