### ISSUE TITLE
Failed to load data for the HomeConnect object

### ISSUE THREAD

**Issue by bkbartk** [ekutner/home-connect-hass#95]
Hello,

After a lot of issues, I migrated from the official app to this one, and yesterday it was working much better. but since of today I don't get any statusses updated anymore. I have 2 devices and both are failing.

my log shows the following
```
This error originated from a custom integration.

Logger: custom_components.home_connect_alt
Source: /config/custom_components/home_connect_alt/__init__.py:133
Integration: Home Connect Alt (documentation, issues)
First occurred: 20:34:58 (1 occurrences)
Last logged: 20:34:58

Failed to load data for the HomeConnect object
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/home_connect_async/homeconnect.py", line 139, in async_load_data
    response = await self._api.async_get('/api/homeappliances')
  File "/usr/local/lib/python3.10/site-packages/home_connect_async/api.py", line 118, in async_get
    return await self._async_request('GET', endpoint)
  File "/usr/local/lib/python3.10/site-packages/home_connect_async/api.py", line 113, in _async_request
    raise HomeConnectError("Failed to get a valid response from Home Connect server", 902)
home_connect_async.common.HomeConnectError: ('Failed to get a valid response from Home Connect server', 902, None, None, None)

```

and the full log shows this:
```
2022-08-17 20:34:07.587 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration browser_mod which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-08-17 20:34:07.596 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration home_connect_alt which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-08-17 20:34:07.604 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-08-17 20:34:07.734 WARNING (MainThread) [homeassistant.config] Key whitelist_external_dirs has been replaced with allowlist_external_dirs. Please update your config
2022-08-17 20:34:52.239 WARNING (MainThread) [homeassistant.setup] Setup of input_datetime is taking over 10 seconds.
2022-08-17 20:34:52.278 WARNING (MainThread) [homeassistant.setup] Setup of input_boolean is taking over 10 seconds.
2022-08-17 20:34:52.282 WARNING (MainThread) [homeassistant.setup] Setup of input_text is taking over 10 seconds.
2022-08-17 20:34:52.285 WARNING (MainThread) [homeassistant.setup] Setup of automation is taking over 10 seconds.
2022-08-17 20:34:52.289 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform template is taking over 10 seconds.
2022-08-17 20:34:52.294 WARNING (MainThread) [homeassistant.components.climate] Setup of climate platform generic_thermostat is taking over 10 seconds.
2022-08-17 20:34:52.297 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform co2signal is taking over 10 seconds.
2022-08-17 20:34:53.431 WARNING (MainThread) [homeassistant.components.number] custom_components.home_connect_alt.number::OptionNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
2022-08-17 20:34:53.455 WARNING (MainThread) [homeassistant.components.number] custom_components.home_connect_alt.number::SettingsNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
2022-08-17 20:34:53.474 DEBUG (MainThread) [home_connect_async.api]
HTTP GET /api/homeappliances (try=1 count=1)
2022-08-17 20:34:57.804 DEBUG (MainThread) [home_connect_async.api] HTTP call failed GET /api/homeappliances
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/home_connect_async/api.py", line 66, in _async_request
response = await self._auth.request(method, endpoint, self._lang, data=data)
File "/usr/local/lib/python3.10/site-packages/home_connect_async/auth.py", line 39, in request
access_token = await self.async_get_access_token()
File "/config/custom_components/home_connect_alt/api.py", line 28, in async_get_access_token
await self._oauth_session.async_ensure_token_valid()
File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 475, in async_ensure_token_valid
new_token = await self.implementation.async_refresh_token(self.token)
File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 89, in async_refresh_token
new_token = await self._async_refresh_token(token)
File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 179, in _async_refresh_token
new_token = await self._token_request(
File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 205, in _token_request
resp.raise_for_status()
File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.home-connect.com/security/oauth/token')
2022-08-17 20:34:57.820 DEBUG (MainThread) [home_connect_async.api]
HTTP GET /api/homeappliances (try=2 count=2)
2022-08-17 20:34:58.032 DEBUG (MainThread) [home_connect_async.api] HTTP call failed GET /api/homeappliances
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/home_connect_async/api.py", line 66, in _async_request
response = await self._auth.request(method, endpoint, self._lang, data=data)
File "/usr/local/lib/python3.10/site-packages/home_connect_async/auth.py", line 39, in request
access_token = await self.async_get_access_token()
File "/config/custom_components/home_connect_alt/api.py", line 28, in async_get_access_token
await self._oauth_session.async_ensure_token_valid()
File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 475, in async_ensure_token_valid
new_token = await self.implementation.async_refresh_token(self.token)
File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 89, in async_refresh_token
new_token = await self._async_refresh_token(token)
File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 179, in _async_refresh_token
new_token = await self._token_request(
File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 205, in _token_request
resp.raise_for_status()
File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.home-connect.com/security/oauth/token')
2022-08-17 20:34:58.034 DEBUG (MainThread) [home_connect_async.api]
HTTP GET /api/homeappliances (try=3 count=3)
2022-08-17 20:34:58.246 DEBUG (MainThread) [home_connect_async.api] HTTP call failed GET /api/homeappliances
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/home_connect_async/api.py", line 66, in _async_request
response = await self._auth.request(method, endpoint, self._lang, data=data)
File "/usr/local/lib/python3.10/site-packages/home_connect_async/auth.py", line 39, in request
access_token = await self.async_get_access_token()
File "/config/custom_components/home_connect_alt/api.py", line 28, in async_get_access_token
await self._oauth_session.async_ensure_token_valid()
File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 475, in async_ensure_token_valid
new_token = await self.implementation.async_refresh_token(self.token)
File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 89, in async_refresh_token
new_token = await self._async_refresh_token(token)
File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 179, in _async_refresh_token
new_token = await self._token_request(
File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 205, in _token_request
resp.raise_for_status()
File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.home-connect.com/security/oauth/token')
2022-08-17 20:34:58.256 WARNING (MainThread) [home_connect_async.homeconnect] Failed to load data from Home Connect (('Failed to get a valid response from Home Connect server', 902, None, None, None))
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/home_connect_async/homeconnect.py", line 139, in async_load_data
response = await self._api.async_get('/api/homeappliances')
File "/usr/local/lib/python3.10/site-packages/home_connect_async/api.py", line 118, in async_get
return await self._async_request('GET', endpoint)
File "/usr/local/lib/python3.10/site-packages/home_connect_async/api.py", line 113, in _async_request
raise HomeConnectError("Failed to get a valid response from Home Connect server", 902)
home_connect_async.common.HomeConnectError: ('Failed to get a valid response from Home Connect server', 902, None, None, None)
2022-08-17 20:34:58.270 ERROR (MainThread) [custom_components.home_connect_alt] Failed to load data for the HomeConnect object
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/home_connect_async/homeconnect.py", line 139, in async_load_data
response = await self._api.async_get('/api/homeappliances')
File "/usr/local/lib/python3.10/site-packages/home_connect_async/api.py", line 118, in async_get
return await self._async_request('GET', endpoint)
File "/usr/local/lib/python3.10/site-packages/home_connect_async/api.py", line 113, in _async_request
raise HomeConnectError("Failed to get a valid response from Home Connect server", 902)
home_connect_async.common.HomeConnectError: ('Failed to get a valid response from Home Connect server', 902, None, None, None)
```

Is there something to find in the log which I can change?

**Comment by ekutner** [comment]
It looks like the server is either responding with a 400 error or no responding at all. I suggest you start by removing the integration and then adding it back again. If that doesn't solve the issue then see the README for instruction on how to enable debug logging and upload a full debug log file.

**Comment by bkbartk** [comment]
reinstalling seems to work, but yesterday it was also working, so let's hope it will still work tomorrow.
No clue what happened.

I totally missed the debug info button, if the issue happens again, I will generate the log.

**Comment by bkbartk** [comment]
The implementation is still working, So I guess reinstalling did the trick, thanks. I will close this one.
